
name: CI


on:
 
  push:
    branches: [ main ]
  

  


jobs:
  
  build:
    
    runs-on: self-hosted

   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Rune test
        run: echo "Hello Runner"
     
      - name: Copy file to home/src
        run: |
          cp -r /home/src/_work/TestCICDrunner/TestCICDrunner/README.md /home/src/
          
