
name: CI


on:
 
  push:
    branches: [ main ]
  

  


jobs:
  
  build:
    
    runs-on: ubuntu-latest

   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Rune test
        run: echo "Hello Runner"
    
          
      - name: Fetch other repo
        run: |
          git clone https://github.com/Nikunj2122/Testrunner.git
          git add .
          git commit -m "Test Commit"
          git push 
          
